'use strict';

module.exports = Object.assign(
  {},
  require('./user-onboarding'),
  require('./tenant-domain-config'),
  require('./ops-leads-domain'),
  require('./ops-advisor-inbox'),
  require('./cobros-reconciliation-domain'),
  require('./recurring-insurance-import'),
  require('./index'),
  require('./bank-accounts'),
  require('./cotcomp-runtime-entry-s438'),
  require('./cotcomp-pilot-intake-s467'),
  require('./cotcomp-pilot-proposal-validation-s471'),
  require('./cotcomp-vehicle-catalog-delivery-s479'),
  require('./cotcomp-vehicle-dropdown-preview-s480'),
  require('./cotcomp-vehicle-combobox-preview-s480a'),
  require('./cotcomp-schema-driven-intake-preview-s485'),
  require('./cotcomp-product-family-completeness-preview-s486'),
  require('./cotcomp-approved-visual-preview-s487'),
  require('./cotcomp-exact-promoted-preview-s488'),
  require('./cotcomp-owner-authorized-comparative-preview-s492'),
  require('./cotcomp-authorized-fidelity-preview-s493'),
  require('./cotcomp-premium-visual-preview-s494'),
  require('./cotcomp-premium-visual-preview-s495'),
  require('./cotcomp-frontend-recovery-preview-s496b'),
  require('./cotcomp-owner-review-s498'),
  require('./cotcomp-owner-review-s499'),
  require('./cotcomp-owner-review-s500'),
  require('./cotcomp-owner-review-s501'),
  require('./cotcomp-public-inbound-lab-s505'),
  require('./cotcomp-owner-review-s506'),
  require('./cotcomp-real-customer-pilot-s508'),
  require('./advisor-lead-attention-s509'),
  require('./siniestros-public-resolver-s512d')
);
